repository_type: pipeline
lint:
  files_exist:
    - assets/nf-core-cmgg/preprocessing_logo_light.png
    - docs/images/nf-core-cmgg/preprocessing_logo_light.png
    - docs/images/nf-core-cmgg/preprocessing_logo_dark.png
