repository_type: pipeline
lint:
  actions_ci: false
  files_exist:
    - .github/workflows/awsfulltest.yml
    - .github/workflows/awstest.yml
    - assets/nf-core-nf-cmgg-preprocessing_logo_dark.png
    - assets/nf-core-nf-cmgg-preprocessing_logo_light.png
    - conf/test_full.config
    - docs/images/nf-core-nf-cmgg-preprocessing_logo_dark.png
    - docs/images/nf-core-nf-cmgg-preprocessing_logo_light.png
  files_unchanged:
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - .gitignore
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  readme:
    - nextflow_badge
