repository_type: pipeline
lint:
  files_exist:
    - .github/workflows/awsfulltest.yml
    - .github/workflows/awstest.yml
    - assets/nf-core-nf-cmgg-preprocessing_logo_light.png
    - CODE_OF_CONDUCT.md
    - docs/images/nf-core-nf-cmgg-preprocessing_logo_dark.png
    - docs/images/nf-core-nf-cmgg-preprocessing_logo_light.png
    - conf/test_full.config
  nextflow_config:
    - manifest.homePage
    - manifest.name
  multiqc_config:
    - report_comment
