name: bam_qc
description: Produces comprehensive statistics from BAM file
keywords:
  - statistics
  - counts
  - hs_metrics
  - wgs_metrics
  - bam
  - sam
  - cram
modules:
  - samtools/stats
  - samtools/idxstats
  - samtools/flagstat
  - picard/collectmultiplemetrics
  - picard/collectwgsmetrics
  - picard/collecthsmetrics
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
  - bai:
      type: file
      description: Index for BAM/CRAM/SAM file
      pattern: "*.{bai,crai,sai}"
  - fasta:
      type: optional file
      description: Reference file the CRAM was created with
      pattern: "*.{fasta,fa}"
  - bait_intervals:
      type: optional file
      description: An interval list file that contains the locations of the baits used.
      pattern: "baits.interval_list"
  - target_intervals:
      type: optional file
      description: An interval list file that contains the locations of the targets.
      pattern: "targets.interval_list"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - stats:
      type: file
      description: File containing samtools stats output
      pattern: "*.{stats}"
  - hs_metrics:
      type: file
      description: Alignment metrics files generated by picard CollectHsMetrics
      pattern: "*_collecthsmetrics.txt"
  - wgs_metrics:
      type: file
      description: Alignment metrics files generated by picard CollectWgsMetrics
      pattern: "*_{metrics}"
  - multiple_metrics:
      type: file
      description: Alignment metrics files generated by picard CollectMultipleMetrics
      pattern: "*_{metrics}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@matthdsm"
