contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #cmgg-preprocessing channel"
    url: https://nfcore.slack.com/channels/cmgg-preprocessing
    about: Discussion about the CenterForMedicalGeneticsGhent/nf-cmgg-preprocessing pipeline
